//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.20 at 09:56:36 AM IST 
//


package org.wso2.carbon.event.execution.manager.core.internal.structure.template.parameter;


import org.wso2.carbon.event.execution.manager.core.internal.structure.template.Parameter;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for OR complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="OR">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OR" type="{}OR" maxOccurs="unbounded"/>
 *         &lt;element name="AND" type="{}AND" maxOccurs="unbounded"/>
 *         &lt;element name="Parameter" type="{}Parameter" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="order" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OR", propOrder = {
        "or",
        "and",
        "parameter"
})
public class OR {

    @XmlElement(name = "OR", required = true)
    protected List<OR> or;
    @XmlElement(name = "AND", required = true)
    protected List<AND> and;
    @XmlElement(name = "Parameter", required = true)
    protected List<Parameter> parameter;
    @XmlAttribute(name = "order", required = true)
    protected String order;

    /**
     * Gets the value of the or property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the or property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOR().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OR }
     *
     *
     */
    public List<OR> getOR() {
        if (or == null) {
            or = new ArrayList<OR>();
        }
        return this.or;
    }

    /**
     * Gets the value of the and property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the and property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAND().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AND }
     *
     *
     */
    public List<AND> getAND() {
        if (and == null) {
            and = new ArrayList<AND>();
        }
        return this.and;
    }

    /**
     * Gets the value of the parameter property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the parameter property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParameter().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Parameter }
     *
     *
     */
    public List<Parameter> getParameter() {
        if (parameter == null) {
            parameter = new ArrayList<Parameter>();
        }
        return this.parameter;
    }

    /**
     * Gets the value of the order property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getOrder() {
        return order;
    }

    /**
     * Sets the value of the order property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setOrder(String value) {
        this.order = value;
    }

}
