<!--
 ~ Copyright (c) 2005-2014, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
 ~
 ~ WSO2 Inc. licenses this file to you under the Apache License,
 ~ Version 2.0 (the "License"); you may not use this file except
 ~ in compliance with the License.
 ~ You may obtain a copy of the License at
 ~
 ~    http://www.apache.org/licenses/LICENSE-2.0
 ~
 ~ Unless required by applicable law or agreed to in writing,
 ~ software distributed under the License is distributed on an
 ~ "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 ~ KIND, either express or implied.  See the License for the
 ~ specific language governing permissions and limitations
 ~ under the License.
-->
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://flow.event.carbon.wso2.org"
                  xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl"
                  xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:xs="http://www.w3.org/2001/XMLSchema"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
                  xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                  targetNamespace="http://flow.event.carbon.wso2.org">
    <wsdl:documentation>EventFlowAdminService</wsdl:documentation>
    <wsdl:types>
        <xs:schema attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://flow.event.carbon.wso2.org">
            <xs:element name="getEventFlow">
                <xs:complexType>
                    <xs:sequence></xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="getEventFlowResponse">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="0" name="return" nillable="true" type="xs:string"></xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:schema>
    </wsdl:types>
    <wsdl:message name="getEventFlowRequest">
        <wsdl:part name="parameters" element="ns:getEventFlow"></wsdl:part>
    </wsdl:message>
    <wsdl:message name="getEventFlowResponse">
        <wsdl:part name="parameters" element="ns:getEventFlowResponse"></wsdl:part>
    </wsdl:message>
    <wsdl:portType name="EventFlowAdminServicePortType">
        <wsdl:operation name="getEventFlow">
            <wsdl:input message="ns:getEventFlowRequest" wsaw:Action="urn:getEventFlow"></wsdl:input>
            <wsdl:output message="ns:getEventFlowResponse" wsaw:Action="urn:getEventFlowResponse"></wsdl:output>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="EventFlowAdminServiceSoap11Binding" type="ns:EventFlowAdminServicePortType">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"></soap:binding>
        <wsdl:operation name="getEventFlow">
            <soap:operation soapAction="urn:getEventFlow" style="document"></soap:operation>
            <wsdl:input>
                <soap:body use="literal"></soap:body>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"></soap:body>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:binding name="EventFlowAdminServiceSoap12Binding" type="ns:EventFlowAdminServicePortType">
        <soap12:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"></soap12:binding>
        <wsdl:operation name="getEventFlow">
            <soap12:operation soapAction="urn:getEventFlow" style="document"></soap12:operation>
            <wsdl:input>
                <soap12:body use="literal"></soap12:body>
            </wsdl:input>
            <wsdl:output>
                <soap12:body use="literal"></soap12:body>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:binding name="EventFlowAdminServiceHttpBinding" type="ns:EventFlowAdminServicePortType">
        <http:binding verb="POST"></http:binding>
        <wsdl:operation name="getEventFlow">
            <http:operation location="getEventFlow"></http:operation>
            <wsdl:input>
                <mime:content type="text/xml" part="parameters"></mime:content>
            </wsdl:input>
            <wsdl:output>
                <mime:content type="text/xml" part="parameters"></mime:content>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="EventFlowAdminService">
        <wsdl:port name="EventFlowAdminServiceHttpsSoap11Endpoint" binding="ns:EventFlowAdminServiceSoap11Binding">
            <soap:address location="https://10.226.129.182:9443/services/EventFlowAdminService.EventFlowAdminServiceHttpsSoap11Endpoint/"></soap:address>
        </wsdl:port>
        <wsdl:port name="EventFlowAdminServiceHttpsSoap12Endpoint" binding="ns:EventFlowAdminServiceSoap12Binding">
            <soap12:address location="https://10.226.129.182:9443/services/EventFlowAdminService.EventFlowAdminServiceHttpsSoap12Endpoint/"></soap12:address>
        </wsdl:port>
        <wsdl:port name="EventFlowAdminServiceHttpsEndpoint" binding="ns:EventFlowAdminServiceHttpBinding">
            <http:address location="https://10.226.129.182:9443/services/EventFlowAdminService.EventFlowAdminServiceHttpsEndpoint/"></http:address>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>